---
engines:
  duplication:
    enabled: true
    exclude_paths:
      - src/examples/*
      - __tests__/*
      - dist/*
  coverage:
    enabled: true
    exclude_paths:
      - src/examples/*
      - __tests__/*
      - dist/*
      - *.md
  metric:
    enabled: true
