dist: bionic
language: node_js
node_js:
#  - "18"
  - "16"
sudo: false
branches:
  only:
    - main
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run test:ci
  - npm run test:coverage
