language: node_js
node_js:
  - "18"
  - "16"
  - "lts"
  - "node"
  - "8"
  - "7"
sudo: false
branches:
  only:
    - main
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run test
  - npm run test-coverage
